var DarkHeresyWeapons = [{
    "name": "Bolt Pistol",
    "availability": "Very Rare",
    "weight": 0,
    "class": "pistol",
    "type": "bolt",
    "range": 30,
    "rateOfFire": {"single": 1, "burst": 2, "full": 0},
    "damage": "2d10k1+5",
    "damageType": "explosive",
    "penetration": 4,
    "clip": {"max": 8, "value": 8},
    "reload": "Full",
    "special": {"tearing": true}
}, {
    "name": "Boltgun",
    "availability": "Very Rare",
    "weight": 7,
    "class": "basic",
    "type": "bolt",
    "range": 100,
    "rateOfFire": {"single": 1, "burst": 3, "full": 0},
    "damage": "2d10k1+5",
    "damageType": "explosive",
    "penetration": 4,
    "clip": {"max": 24, "value": 24},
    "reload": "Full",
    "special": {"tearing": true}
}, {
    "name": "Godwyn-Deaz Bolt Pistol",
    "availability": "Extremely Rare",
    "weight": 3,
    "class": "pistol",
    "type": "bolt",
    "range": 40,
    "rateOfFire": {"single": 1, "burst": 2, "full": 0},
    "damage": "2d10k1+5",
    "damageType": "explosive",
    "penetration": 4,
    "clip": {"max": 10, "value": 10},
    "reload": "Full",
    "special": {"reliable": true, "tearing": true}
}, {
    "name": "Godwyn-Deaz Bolter",
    "availability": "Very Rare",
    "weight": 6,
    "class": "basic",
    "type": "bolt",
    "range": 90,
    "rateOfFire": {"single": 1, "burst": 2, "full": 0},
    "damage": "2d10k1+5",
    "damageType": "explosive",
    "penetration": 4,
    "clip": {"max": 30, "value": 30},
    "reload": "Full",
    "special": {"reliable": true, "tearing": true}
}, {
    "name": "Godwyn-Deaz Heavy Bolter",
    "availability": "Extremely Rare",
    "weight": 35,
    "class": "heavy",
    "type": "bolt",
    "range": 140,
    "rateOfFire": {"single": 0, "burst": 0, "full": 6},
    "damage": "2d10k1+8",
    "damageType": "explosive",
    "penetration": 5,
    "clip": {"max": 80, "value": 80},
    "reload": "Full",
    "special": {"reliable": true, "tearing": true}
}, {
    "name": "Godwyn-Deaz Storm Bolter",
    "availability": "Near Unique",
    "weight": 8,
    "class": "basic",
    "type": "bolt",
    "range": 80,
    "rateOfFire": {"single": 1, "burst": 2, "full": 4},
    "damage": "2d10k1+5",
    "damageType": "explosive",
    "penetration": 4,
    "clip": {"max": 60, "value": 60},
    "reload": "Full",
    "special": {"reliable": true, "storm": true, "tearing": true}
}, {
    "name": "Heavy Bolter",
    "availability": "Very Rare",
    "weight": 40,
    "class": "heavy",
    "type": "bolt",
    "range": 150,
    "rateOfFire": {"single": 0, "burst": 0, "full": 6},
    "damage": "2d10k1+8",
    "damageType": "explosive",
    "penetration": 5,
    "clip": {"max": 60, "value": 60},
    "reload": "Full",
    "special": {"tearing": true}
}, {
    "name": "Psycannon",
    "availability": "Near Unique",
    "weight": 20,
    "class": "heavy",
    "type": "bolt",
    "range": 120,
    "rateOfFire": {"single": 0, "burst": 2, "full": 5},
    "damage": "3d10k2+5",
    "damageType": "explosive",
    "penetration": 5,
    "clip": {"max": 40, "value": 40},
    "reload": "3 Full",
    "special": {"daemonbane": true, "reliable": true, "tearing": true}
}, {
    "name": "Storm Bolter",
    "availability": "Extremely Rare",
    "weight": 9,
    "class": "basic",
    "type": "bolt",
    "range": 90,
    "rateOfFire": {"single": 1, "burst": 2, "full": 4},
    "damage": "2d10k1+5",
    "damageType": "explosive",
    "penetration": 4,
    "clip": {"max": 60, "value": 60},
    "reload": "Full",
    "special": {"storm": true, "tearing": true}
}, {
    "name": "Chainaxe",
    "availability": "Scarce",
    "weight": 13,
    "class": "melee",
    "type": "chain",
    "range": 0,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "2d10k1+4",
    "damageType": "rending",
    "penetration": 2,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"tearing": true, "two-handed": true}
}, {
    "name": "Chainblade",
    "availability": "Scarce",
    "weight": 2,
    "class": "melee",
    "type": "chain",
    "range": 0,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "2d10k1+1",
    "damageType": "rending",
    "penetration": 1,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"tearing": true}
}, {
    "name": "Chainsword",
    "availability": "Average",
    "weight": 6,
    "class": "melee",
    "type": "chain",
    "range": 0,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "2d10k1+2",
    "damageType": "rending",
    "penetration": 2,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"balanced": true, "tearing": true}
}, {
    "name": "Eviscerator",
    "availability": "Very Rare",
    "weight": 15,
    "class": "melee",
    "type": "chain",
    "range": 0,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "",
    "damageType": "rending",
    "penetration": 9,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"razor-sharp": true, "tearing": true, "two-handed": true, "unwieldy": true}
}, {
    "name": "Condemnor",
    "availability": "Rare",
    "weight": 8,
    "class": "basic",
    "type": "exotic",
    "range": 100,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "1d10+4",
    "damageType": "rending",
    "penetration": 2,
    "clip": {"max": 1, "value": 1},
    "reload": "2 Full",
    "special": {"accurate": true, "reliable": true}
}, {
    "name": "Digi-Weapon",
    "availability": "Near Unique",
    "weight": 0,
    "class": "pistol",
    "type": "exotic",
    "range": 3,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "",
    "damageType": "impact",
    "penetration": 0,
    "clip": {"max": 1, "value": 1},
    "reload": "",
    "special": {}
}, {
    "name": "Firesprite Needler",
    "availability": "Extremely Rare",
    "weight": 0,
    "class": "pistol",
    "type": "exotic",
    "range": 30,
    "rateOfFire": {"single": 0, "burst": 4, "full": 8},
    "damage": "1d10+2",
    "damageType": "rending",
    "penetration": 2,
    "clip": {"max": 16, "value": 16},
    "reload": "2 Full",
    "special": {"inaccurate": true, "toxic": 2}
}, {
    "name": "Ghost Blade",
    "availability": "Extremely Rare",
    "weight": 6,
    "class": "melee",
    "type": "exotic",
    "range": 0,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "1d10+5",
    "damageType": "energy",
    "penetration": 6,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"felling": 4, "razor-sharp": true, "overheats": true}
}, {
    "name": "Grav Pistol",
    "availability": "Near Unique",
    "weight": 3,
    "class": "pistol",
    "type": "exotic",
    "range": 15,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "1d10+3",
    "damageType": "impact",
    "penetration": 6,
    "clip": {"max": 6, "value": 6},
    "reload": "Full",
    "special": {"concussive": 1, "graviton": true}
}, {
    "name": "Graviton Grenade",
    "availability": "Near Unique",
    "weight": 1,
    "class": "thrown",
    "type": "exotic",
    "range": 0,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "1d10+7",
    "damageType": "impact",
    "penetration": 1,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"blast": 3, "concussive": 3, "graviton": true}
}, {
    "name": "Graviton Gun",
    "availability": "Extremely Rare",
    "weight": 6,
    "class": "basic",
    "type": "exotic",
    "range": 30,
    "rateOfFire": {"single": 1, "burst": 3, "full": 0},
    "damage": "1d10+6",
    "damageType": "impact",
    "penetration": 8,
    "clip": {"max": 9, "value": 9},
    "reload": "2 Full",
    "special": {"concussive": 2, "graviton": true}
}, {
    "name": "Graviton Hammer",
    "availability": "Near Unique",
    "weight": 8,
    "class": "melee",
    "type": "exotic",
    "range": 0,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "2d10+5",
    "damageType": "impact",
    "penetration": 7,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"concussive": 3, "graviton": true}
}, {
    "name": "Hellrifle",
    "availability": "Very Rare",
    "weight": 10,
    "class": "basic",
    "type": "exotic",
    "range": 300,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "1d10+4",
    "damageType": "rending",
    "penetration": 4,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"felling": 2}
}, {
    "name": "Integration Cannon",
    "availability": "Near Unique",
    "weight": 65,
    "class": "heavy",
    "type": "exotic",
    "range": 100,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "4d10+4",
    "damageType": "impact",
    "penetration": 8,
    "clip": {"max": 6, "value": 6},
    "reload": "3 Full",
    "special": {"blast": 5, "concussive": 0, "inaccurate": true}
}, {
    "name": "Needle Pistol",
    "availability": "Very Rare",
    "weight": 0,
    "class": "pistol",
    "type": "exotic",
    "range": 30,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "1d10",
    "damageType": "rending",
    "penetration": 0,
    "clip": {"max": 6, "value": 6},
    "reload": "Full",
    "special": {"accurate": true, "felling": 1, "toxic": 5}
}, {
    "name": "Needle Rifle",
    "availability": "Very Rare",
    "weight": 2,
    "class": "basic",
    "type": "exotic",
    "range": 180,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "1d10",
    "damageType": "rending",
    "penetration": 0,
    "clip": {"max": 6, "value": 6},
    "reload": "2 Full",
    "special": {"accurate": true, "felling": 1, "toxic": 5}
}, {
    "name": "Purgatus Crossbow",
    "availability": "Rare",
    "weight": 16,
    "class": "basic",
    "type": "exotic",
    "range": 50,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "1d10+5",
    "damageType": "impact",
    "penetration": 0,
    "clip": {"max": 5, "value": 5},
    "reload": "2 Full",
    "special": {"reliable": true}
}, {
    "name": "Quillgun",
    "availability": "Very Rare",
    "weight": 6,
    "class": "basic",
    "type": "exotic",
    "range": 120,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "",
    "damageType": "impact",
    "penetration": 0,
    "clip": {"max": 3, "value": 3},
    "reload": "Full",
    "special": {}
}, {
    "name": "Silver Shield",
    "availability": "Extremely Rare",
    "weight": 5,
    "class": "melee",
    "type": "exotic",
    "range": 0,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "1d5+1",
    "damageType": "impact",
    "penetration": 1,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"defensive": true}
}, {
    "name": "Silverseine Launcher",
    "availability": "Very Rare",
    "weight": 25,
    "class": "heavy",
    "type": "exotic",
    "range": 60,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "1d10",
    "damageType": "impact",
    "penetration": 0,
    "clip": {"max": 1, "value": 1},
    "reload": "2 Full",
    "special": {"blast": 4, "reliable": true, "sanctified": true, "snare": 2}
}, {
    "name": "Web Pistol",
    "availability": "Very Rare",
    "weight": 0,
    "class": "pistol",
    "type": "exotic",
    "range": 30,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "",
    "damageType": "impact",
    "penetration": 0,
    "clip": {"max": 1, "value": 1},
    "reload": "Full",
    "special": {"snare": 0}
}, {
    "name": "Webber",
    "availability": "Rare",
    "weight": 8,
    "class": "basic",
    "type": "exotic",
    "range": 50,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "",
    "damageType": "impact",
    "penetration": 0,
    "clip": {"max": 1, "value": 1},
    "reload": "2 Full",
    "special": {"blast": 5, "snare": 1}
}, {
    "name": "Fire Bomb",
    "availability": "Plentiful",
    "weight": 0,
    "class": "thrown",
    "type": "explosive",
    "range": 0,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "1d10+2",
    "damageType": "energy",
    "penetration": 0,
    "clip": {"max": 1, "value": 1},
    "reload": "",
    "special": {"blast": 2, "flame": true}
}, {
    "name": "Melta Bomb",
    "availability": "Very Rare",
    "weight": 12,
    "class": "",
    "type": "explosive",
    "range": 0,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "6d10",
    "damageType": "energy",
    "penetration": 12,
    "clip": {"max": 1, "value": 1},
    "reload": "",
    "special": {"blast": 2, "flame": true, "melta": true}
}, {
    "name": "Brazier of Holy Fire",
    "availability": "Very Rare",
    "weight": 6,
    "class": "melee",
    "type": "flame",
    "range": 0,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "1d10+5",
    "damageType": "energy",
    "penetration": 3,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"flame": true, "unbalanced": true}
}, {
    "name": "Cerberus Heavy Flamer",
    "availability": "Very Rare",
    "weight": 40,
    "class": "heavy",
    "type": "flame",
    "range": 30,
    "rateOfFire": {"single": 1, "burst": 2, "full": 0},
    "damage": "1d10+5",
    "damageType": "energy",
    "penetration": 3,
    "clip": {"max": 8, "value": 8},
    "reload": "2 Full",
    "special": {"flame": true, "reliable": true, "spray": true}
}, {
    "name": "Fire Gauntlets",
    "availability": "Very Rare",
    "weight": 1,
    "class": "melee",
    "type": "flame",
    "range": 0,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "1d10",
    "damageType": "impact",
    "penetration": 2,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"flame": true, "unbalanced": true}
}, {
    "name": "Flamer",
    "availability": "Scarce",
    "weight": 6,
    "class": "basic",
    "type": "flame",
    "range": 20,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "1d10+4",
    "damageType": "energy",
    "penetration": 2,
    "clip": {"max": 6, "value": 6},
    "reload": "2 Full",
    "special": {"flame": true, "spray": true}
}, {
    "name": "Gorgon Chemical Flamer",
    "availability": "Very Rare",
    "weight": 8,
    "class": "basic",
    "type": "flame",
    "range": 20,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "1d10+4",
    "damageType": "energy",
    "penetration": 2,
    "clip": {"max": 6, "value": 6},
    "reload": "2 Full",
    "special": {"corrosive": true, "felling": 1, "flame": true, "spray": true, "toxic": 2}
}, {
    "name": "Hand Flamer",
    "availability": "Rare",
    "weight": 0,
    "class": "pistol",
    "type": "flame",
    "range": 10,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "1d10+4",
    "damageType": "energy",
    "penetration": 2,
    "clip": {"max": 2, "value": 2},
    "reload": "2 Full",
    "special": {"flame": true, "spray": true}
}, {
    "name": "Heavy Flamer",
    "availability": "Rare",
    "weight": 45,
    "class": "heavy",
    "type": "flame",
    "range": 30,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "1d10+5",
    "damageType": "energy",
    "penetration": 4,
    "clip": {"max": 10, "value": 10},
    "reload": "2 Full",
    "special": {"flame": true, "spray": true}
}, {
    "name": "Hydra Flamer Array",
    "availability": "Very Rare",
    "weight": 10,
    "class": "basic",
    "type": "flame",
    "range": 8,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "1d10+4",
    "damageType": "energy",
    "penetration": 2,
    "clip": {"max": 10, "value": 10},
    "reload": "2 Full",
    "special": {"flame": true, "proven": 3, "spray": true}
}, {
    "name": "Incinerator",
    "availability": "Extremely Rare",
    "weight": 3,
    "class": "basic",
    "type": "flame",
    "range": 30,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "1d10+6",
    "damageType": "energy",
    "penetration": 6,
    "clip": {"max": 10, "value": 10},
    "reload": "2 Full",
    "special": {"daemonbane": true, "flame": true, "spray": true}
}, {
    "name": "Animus Hammer",
    "availability": "Near Unique",
    "weight": 8,
    "class": "melee",
    "type": "force",
    "range": 0,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "2d10+10",
    "damageType": "energy",
    "penetration": 4,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"daemonbane": true, "force": true, "power-field": true, "unwieldy": true}
}, {
    "name": "Force Hammer",
    "availability": "Extremely Rare",
    "weight": 10,
    "class": "melee",
    "type": "force",
    "range": 0,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "2d10",
    "damageType": "rending",
    "penetration": 0,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"force": true, "unbalanced": true}
}, {
    "name": "Force Staff",
    "availability": "Extremely Rare",
    "weight": 2,
    "class": "melee",
    "type": "force",
    "range": 0,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "1d10",
    "damageType": "impact",
    "penetration": 2,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"force": true, "two-handed": true}
}, {
    "name": "Force Sword",
    "availability": "Near Unique",
    "weight": 5,
    "class": "melee",
    "type": "force",
    "range": 0,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "1d10+1",
    "damageType": "rending",
    "penetration": 2,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"balanced": true, "force": true}
}, {
    "name": "Nemesis Daemon Hammer",
    "availability": "Near Unique",
    "weight": 10,
    "class": "melee",
    "type": "force",
    "range": 0,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "2d10+1",
    "damageType": "energy",
    "penetration": 8,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"daemonbane": true, "force": true, "power-field": true, "unwieldy": true}
}, {
    "name": "Santus Hammer",
    "availability": "Near Unique",
    "weight": 6,
    "class": "melee",
    "type": "force",
    "range": 0,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "2d10+6",
    "damageType": "energy",
    "penetration": 4,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"balanced": true, "concussive": 4, "daemonbane": true, "force": true, "power-field": true}
}, {
    "name": "Tempus Hammer",
    "availability": "Near Unique",
    "weight": 14,
    "class": "melee",
    "type": "force",
    "range": 0,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "2d10+4",
    "damageType": "energy",
    "penetration": 6,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"daemonbane": true, "force": true, "power-field": true, "unwieldy": true}
}, {
    "name": "Ironfaith Incense Grenade",
    "availability": "Rare",
    "weight": 0,
    "class": "thrown",
    "type": "explosive",
    "range": 0,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "1d10",
    "damageType": "explosive",
    "penetration": 0,
    "clip": {"max": 1, "value": 1},
    "reload": "",
    "special": {"daemonbane": true, "sanctified": true, "smoke": 3}
}, {
    "name": "Abyssal Charge",
    "availability": "Extremely Rare",
    "weight": 0,
    "class": "thrown",
    "type": "explosive",
    "range": 0,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "1d10+4",
    "damageType": "explosive",
    "penetration": 4,
    "clip": {"max": 1, "value": 1},
    "reload": "",
    "special": {"blast": 3, "crippling": 2, "tainted": true}
}, {
    "name": "Argent Globe",
    "availability": "Extremely Rare",
    "weight": 0,
    "class": "thrown",
    "type": "explosive",
    "range": 0,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "2d10",
    "damageType": "explosive",
    "penetration": 2,
    "clip": {"max": 1, "value": 1},
    "reload": "",
    "special": {"blast": 3, "crippling": 3, "sanctified": true}
}, {
    "name": "Blind Grenade",
    "availability": "Scarce",
    "weight": 0,
    "class": "thrown",
    "type": "explosive",
    "range": 0,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "",
    "damageType": "impact",
    "penetration": 0,
    "clip": {"max": 1, "value": 1},
    "reload": "",
    "special": {"smoke": 2}
}, {
    "name": "Choke Grenade",
    "availability": "Scarce",
    "weight": 0,
    "class": "thrown",
    "type": "explosive",
    "range": 0,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "Special",
    "damageType": "impact",
    "penetration": 0,
    "clip": {"max": 1, "value": 1},
    "reload": "",
    "special": {"blast": 3}
}, {
    "name": "Frag Grenade",
    "availability": "Common",
    "weight": 0,
    "class": "thrown",
    "type": "explosive",
    "range": 0,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "2d10",
    "damageType": "explosive",
    "penetration": 0,
    "clip": {"max": 1, "value": 1},
    "reload": "",
    "special": {"blast": 3}
}, {
    "name": "Frag Missile",
    "availability": "Average",
    "weight": 1,
    "class": "",
    "type": "explosive",
    "range": 0,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "2d10+2",
    "damageType": "explosive",
    "penetration": 2,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"blast": 5}
}, {
    "name": "Hallucinogen Grenade",
    "availability": "Scarce",
    "weight": 0,
    "class": "thrown",
    "type": "explosive",
    "range": 0,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "",
    "damageType": "impact",
    "penetration": 0,
    "clip": {"max": 1, "value": 1},
    "reload": "",
    "special": {"blast": 6, "hallucinogenic": true}
}, {
    "name": "Haywire Grenade",
    "availability": "Very Rare",
    "weight": 0,
    "class": "thrown",
    "type": "explosive",
    "range": 0,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "",
    "damageType": "impact",
    "penetration": 0,
    "clip": {"max": 1, "value": 1},
    "reload": "",
    "special": {"haywire": 2}
}, {
    "name": "Krak Grenade",
    "availability": "Rare",
    "weight": 0,
    "class": "thrown",
    "type": "explosive",
    "range": 0,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "2d10+4",
    "damageType": "explosive",
    "penetration": 6,
    "clip": {"max": 1, "value": 1},
    "reload": "",
    "special": {"concussive": 0}
}, {
    "name": "Krak Missile",
    "availability": "Scarce",
    "weight": 1,
    "class": "",
    "type": "explosive",
    "range": 0,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "3d10+8",
    "damageType": "explosive",
    "penetration": 8,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"concussive": 3, "proven": 2}
}, {
    "name": "Photon Flash Grenade",
    "availability": "Rare",
    "weight": 0,
    "class": "thrown",
    "type": "explosive",
    "range": 0,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "",
    "damageType": "impact",
    "penetration": 0,
    "clip": {"max": 1, "value": 1},
    "reload": "",
    "special": {"blast": 6}
}, {
    "name": "Psychotroke Grenade",
    "availability": "Rare",
    "weight": 0,
    "class": "thrown",
    "type": "explosive",
    "range": 0,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "",
    "damageType": "impact",
    "penetration": 0,
    "clip": {"max": 1, "value": 1},
    "reload": "",
    "special": {"blast": 3, "hallucinogenic": 4}
}, {
    "name": "Psyk-Out Grenade",
    "availability": "Extremely Rare",
    "weight": 1,
    "class": "thrown",
    "type": "explosive",
    "range": 0,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "1d10",
    "damageType": "explosive",
    "penetration": 0,
    "clip": {"max": 1, "value": 1},
    "reload": "",
    "special": {"blast": 3, "smoke": 3}
}, {
    "name": "Psyk-Out Grenade",
    "availability": "Extremely Rare",
    "weight": 1,
    "class": "thrown",
    "type": "explosive",
    "range": 0,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "1d10",
    "damageType": "explosive",
    "penetration": 0,
    "clip": {"max": 1, "value": 1},
    "reload": "",
    "special": {"blast": 3, "smoke": 3}
}, {
    "name": "Rad Grenade",
    "availability": "Very Rare",
    "weight": 1,
    "class": "thrown",
    "type": "explosive",
    "range": 0,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "1d10",
    "damageType": "energy",
    "penetration": 0,
    "clip": {"max": 1, "value": 1},
    "reload": "",
    "special": {"blast": 2}
}, {
    "name": "Smoke Grenade",
    "availability": "Common",
    "weight": 0,
    "class": "thrown",
    "type": "explosive",
    "range": 0,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "",
    "damageType": "impact",
    "penetration": 0,
    "clip": {"max": 1, "value": 1},
    "reload": "",
    "special": {"smoke": 4}
}, {
    "name": "Spore Bomb",
    "availability": "Very Rare",
    "weight": 2,
    "class": "thrown",
    "type": "explosive",
    "range": 0,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "",
    "damageType": "impact",
    "penetration": 0,
    "clip": {"max": 1, "value": 1},
    "reload": "",
    "special": {"blast": 5}
}, {
    "name": "Stun Grenade",
    "availability": "Common",
    "weight": 0,
    "class": "thrown",
    "type": "explosive",
    "range": 0,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "",
    "damageType": "impact",
    "penetration": 0,
    "clip": {"max": 1, "value": 1},
    "reload": "",
    "special": {"blast": 3, "concussive": 2}
}, {
    "name": "Tears of the Emperor",
    "availability": "Near Unique",
    "weight": 0,
    "class": "thrown",
    "type": "explosive",
    "range": 0,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "1d10",
    "damageType": "explosive",
    "penetration": 0,
    "clip": {"max": 1, "value": 1},
    "reload": "",
    "special": {"blast": 2, "sanctified": true}
}, {
    "name": "Web Grenade",
    "availability": "Rare",
    "weight": 0,
    "class": "thrown",
    "type": "explosive",
    "range": 0,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "",
    "damageType": "impact",
    "penetration": 0,
    "clip": {"max": 1, "value": 1},
    "reload": "",
    "special": {"blast": 3, "snare": 2}
}, {
    "name": "Whitefire Grenade",
    "availability": "Extremely Rare",
    "weight": 1,
    "class": "thrown",
    "type": "explosive",
    "range": 0,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "1d10+4",
    "damageType": "explosive",
    "penetration": 3,
    "clip": {"max": 1, "value": 1},
    "reload": "",
    "special": {"blast": 3, "corrosive": true, "flame": true, "smoke": 5, "toxic": 2}
}, {
    "name": "Hot-shot Lasgun",
    "availability": "Rare",
    "weight": 6,
    "class": "basic",
    "type": "las",
    "range": 60,
    "rateOfFire": {"single": 1, "burst": 3, "full": 0},
    "damage": "1d10+4",
    "damageType": "energy",
    "penetration": 7,
    "clip": {"max": 30, "value": 30},
    "reload": "2 Full",
    "special": {}
}, {
    "name": "Hot-shot Laspistol",
    "availability": "Rare",
    "weight": 4,
    "class": "pistol",
    "type": "las",
    "range": 20,
    "rateOfFire": {"single": 1, "burst": 2, "full": 0},
    "damage": "1d10+4",
    "damageType": "energy",
    "penetration": 7,
    "clip": {"max": 40, "value": 40},
    "reload": "2 Full",
    "special": {}
}, {
    "name": "Lasgun",
    "availability": "Common",
    "weight": 4,
    "class": "basic",
    "type": "las",
    "range": 100,
    "rateOfFire": {"single": 1, "burst": 3, "full": 0},
    "damage": "1d10+3",
    "damageType": "energy",
    "penetration": 0,
    "clip": {"max": 60, "value": 60},
    "reload": "Full",
    "special": {"reliable": true}
}, {
    "name": "Laslock",
    "availability": "Plentiful",
    "weight": 4,
    "class": "basic",
    "type": "las",
    "range": 70,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "1d10+4",
    "damageType": "energy",
    "penetration": 0,
    "clip": {"max": 1, "value": 1},
    "reload": "Half",
    "special": {"unreliable": true}
}, {
    "name": "Laspistol",
    "availability": "Common",
    "weight": 0,
    "class": "pistol",
    "type": "las",
    "range": 30,
    "rateOfFire": {"single": 1, "burst": 2, "full": 0},
    "damage": "1d10+2",
    "damageType": "energy",
    "penetration": 0,
    "clip": {"max": 30, "value": 30},
    "reload": "Half",
    "special": {"reliable": true}
}, {
    "name": "Long-Las",
    "availability": "Scarce",
    "weight": 0,
    "class": "basic",
    "type": "las",
    "range": 150,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "1d10+3",
    "damageType": "energy",
    "penetration": 1,
    "clip": {"max": 40, "value": 40},
    "reload": "Full",
    "special": {"accurate": true, "felling": 4, "reliable": true}
}, {
    "name": "Grenade Launcher",
    "availability": "Average",
    "weight": 12,
    "class": "basic",
    "type": "launcher",
    "range": 60,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "",
    "damageType": "impact",
    "penetration": 0,
    "clip": {"max": 6, "value": 6},
    "reload": "2 Full",
    "special": {}
}, {
    "name": "Missile Launcher",
    "availability": "Rare",
    "weight": 35,
    "class": "heavy",
    "type": "launcher",
    "range": 300,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "",
    "damageType": "impact",
    "penetration": 0,
    "clip": {"max": 1, "value": 1},
    "reload": "Full",
    "special": {}
}, {
    "name": "Arquebus",
    "availability": "Common",
    "weight": 8,
    "class": "basic",
    "type": "low-tech",
    "range": 45,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "2d10+2",
    "damageType": "impact",
    "penetration": 2,
    "clip": {"max": 1, "value": 1},
    "reload": "2 Full",
    "special": {"concussive": 1, "inaccurate": true, "unreliable": true}
}, {
    "name": "Axe of Retribution",
    "availability": "Near Unique",
    "weight": 8,
    "class": "melee",
    "type": "low-tech",
    "range": 0,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "2d10",
    "damageType": "rending",
    "penetration": 6,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"felling": 2, "sanctified": true}
}, {
    "name": "Bolas",
    "availability": "Average",
    "weight": 0,
    "class": "thrown",
    "type": "low-tech",
    "range": 10,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "",
    "damageType": "impact",
    "penetration": 0,
    "clip": {"max": 1, "value": 1},
    "reload": "",
    "special": {"inaccurate": true, "snare": true}
}, {
    "name": "Bow",
    "availability": "Common",
    "weight": 2,
    "class": "basic",
    "type": "low-tech",
    "range": 30,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "1d10",
    "damageType": "rending",
    "penetration": 0,
    "clip": {"max": 1, "value": 1},
    "reload": "Half",
    "special": {"primitive": 6, "reliable": true}
}, {
    "name": "Castigator Heavy Crossbow",
    "availability": "Scarce",
    "weight": 12,
    "class": "heavy",
    "type": "low-tech",
    "range": 70,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "1d10+6",
    "damageType": "impact",
    "penetration": 1,
    "clip": {"max": 14, "value": 14},
    "reload": "2 Full",
    "special": {"concussive": 2, "reliable": true}
}, {
    "name": "Crossbow",
    "availability": "Common",
    "weight": 3,
    "class": "basic",
    "type": "low-tech",
    "range": 30,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "1d10",
    "damageType": "rending",
    "penetration": 0,
    "clip": {"max": 1, "value": 1},
    "reload": "2 Full",
    "special": {"primitive": 7}
}, {
    "name": "Deliverance Light Crossbow",
    "availability": "Rare",
    "weight": 1,
    "class": "pistol",
    "type": "low-tech",
    "range": 15,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "1d10",
    "damageType": "rending",
    "penetration": 0,
    "clip": {"max": 1, "value": 1},
    "reload": "Half",
    "special": {"primitive": 7}
}, {
    "name": "Drakes Claw",
    "availability": "Rare",
    "weight": 6,
    "class": "heavy",
    "type": "low-tech",
    "range": 200,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "3d10k2+2",
    "damageType": "explosive",
    "penetration": 2,
    "clip": {"max": 1, "value": 1},
    "reload": "",
    "special": {"blast": 3, "crippling": 1, "inaccurate": true, "primitive": 7, "tearing": true}
}, {
    "name": "Flail of Chastisement",
    "availability": "Rare",
    "weight": 3,
    "class": "melee",
    "type": "low-tech",
    "range": 0,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "1d10+8",
    "damageType": "rending",
    "penetration": 2,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"crippling": 2, "flexible": true, "primitive": 8, "snare": 2}
}, {
    "name": "Flintlock Pistol",
    "availability": "Common",
    "weight": 3,
    "class": "pistol",
    "type": "low-tech",
    "range": 15,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "1d10+2",
    "damageType": "impact",
    "penetration": 0,
    "clip": {"max": 1, "value": 1},
    "reload": "2 Full",
    "special": {"inaccurate": true, "primitive": 8, "unreliable": true}
}, {
    "name": "Great Weapon",
    "availability": "Scarce",
    "weight": 7,
    "class": "melee",
    "type": "low-tech",
    "range": 0,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "2d10",
    "damageType": "rending",
    "penetration": 0,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"unbalanced": true, "two-handed": true}
}, {
    "name": "Hunting Lance",
    "availability": "Scarce",
    "weight": 4,
    "class": "melee",
    "type": "low-tech",
    "range": 0,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "2d10+3",
    "damageType": "explosive",
    "penetration": 7,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"concussive": 3}
}, {
    "name": "Improvised",
    "availability": "",
    "weight": 0,
    "class": "melee",
    "type": "low-tech",
    "range": 0,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "1d10-2",
    "damageType": "impact",
    "penetration": 0,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"primitive": 7, "unbalanced": true}
}, {
    "name": "Knife",
    "availability": "Plentiful",
    "weight": 1,
    "class": "melee",
    "type": "low-tech",
    "range": 0,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "1d5",
    "damageType": "rending",
    "penetration": 0,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {}
}, {
    "name": "Knife",
    "availability": "Plentiful",
    "weight": 1,
    "class": "thrown",
    "type": "low-tech",
    "range": 5,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "1d5",
    "damageType": "rending",
    "penetration": 0,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {}
}, {
    "name": "Longflame",
    "availability": "Rare",
    "weight": 6,
    "class": "heavy",
    "type": "low-tech",
    "range": 200,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "1d10",
    "damageType": "rending",
    "penetration": 0,
    "clip": {"max": 1, "value": 1},
    "reload": "",
    "special": {"blast": 4, "flame": true, "inaccurate": true, "primitive": 8}
}, {
    "name": "Man-Catcher",
    "availability": "Scarce",
    "weight": 8,
    "class": "melee",
    "type": "low-tech",
    "range": 2,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "1d10",
    "damageType": "impact",
    "penetration": 0,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"snare": 4, "unwieldy": true}
}, {
    "name": "Musket",
    "availability": "Common",
    "weight": 7,
    "class": "basic",
    "type": "low-tech",
    "range": 30,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "1d10+3",
    "damageType": "impact",
    "penetration": 0,
    "clip": {"max": 1, "value": 1},
    "reload": "2 Full",
    "special": {"inaccurate": true, "primitive": 8, "unreliable": true}
}, {
    "name": "Praesidium Protectiva",
    "availability": "Very Rare",
    "weight": 14,
    "class": "melee",
    "type": "low-tech",
    "range": 0,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "1d10",
    "damageType": "impact",
    "penetration": 0,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"defensive": true}
}, {
    "name": "Rune Weapon (Sword)",
    "availability": "Near Unique",
    "weight": 3,
    "class": "melee",
    "type": "low-tech",
    "range": 0,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "",
    "damageType": "rending",
    "penetration": 0,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"balanced": true, "tainted": true, "tearing": true, "vengeful": 8}
}, {
    "name": "Shield",
    "availability": "Common",
    "weight": 3,
    "class": "melee",
    "type": "low-tech",
    "range": 0,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "1d5",
    "damageType": "impact",
    "penetration": 0,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"defensive": true}
}, {
    "name": "Snapper Repeating Rifle",
    "availability": "Very Rare",
    "weight": 45,
    "class": "basic",
    "type": "low-tech",
    "range": 50,
    "rateOfFire": {"single": 1, "burst": 2, "full": 0},
    "damage": "1d10+3",
    "damageType": "impact",
    "penetration": 0,
    "clip": {"max": 8, "value": 8},
    "reload": "2 Full",
    "special": {"inaccurate": true, "overheats": true, "primitive": 8, "unreliable": true}
}, {
    "name": "Spear",
    "availability": "Common",
    "weight": 3,
    "class": "melee",
    "type": "low-tech",
    "range": 0,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "1d10",
    "damageType": "rending",
    "penetration": 0,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"primitive": 8, "two-handed": true}
}, {
    "name": "Staff",
    "availability": "Plentiful",
    "weight": 3,
    "class": "melee",
    "type": "low-tech",
    "range": 0,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "1d10",
    "damageType": "impact",
    "penetration": 0,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"balanced": true, "primitive": 7, "two-handed": true}
}, {
    "name": "Stealth Claw",
    "availability": "Very Rare",
    "weight": 0,
    "class": "melee",
    "type": "low-tech",
    "range": 0,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "1d10+4",
    "damageType": "rending",
    "penetration": 4,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"felling": 2, "razor-sharp": true, "sanctified": true}
}, {
    "name": "Sword",
    "availability": "Common",
    "weight": 3,
    "class": "melee",
    "type": "low-tech",
    "range": 0,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "1d10",
    "damageType": "rending",
    "penetration": 0,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"balanced": true}
}, {
    "name": "Truncheon",
    "availability": "Plentiful",
    "weight": 2,
    "class": "melee",
    "type": "low-tech",
    "range": 0,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "1d10",
    "damageType": "impact",
    "penetration": 0,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"primitive": 7}
}, {
    "name": "Unarmed",
    "availability": "",
    "weight": 0,
    "class": "melee",
    "type": "low-tech",
    "range": 0,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "1d5-3",
    "damageType": "impact",
    "penetration": 0,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {}
}, {
    "name": "Wailing Trident",
    "availability": "Very Rare",
    "weight": 9,
    "class": "melee/ thrown",
    "type": "low-tech",
    "range": 6,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "1d10+8",
    "damageType": "rending",
    "penetration": 4,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"balanced": true, "crippling": 3, "felling": 3, "sanctified": true}
}, {
    "name": "Warhammer",
    "availability": "Scarce",
    "weight": 0,
    "class": "melee",
    "type": "low-tech",
    "range": 0,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "1d10+3",
    "damageType": "impact",
    "penetration": 1,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"concussive": 1, "primitive": 8, "two-handed": true}
}, {
    "name": "Whip",
    "availability": "Average",
    "weight": 2,
    "class": "melee",
    "type": "low-tech",
    "range": 3,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "1d10",
    "damageType": "rending",
    "penetration": 0,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"flexible": true, "primitive": 6}
}, {
    "name": "Inferno Pistol",
    "availability": "Near Unique",
    "weight": 3,
    "class": "pistol",
    "type": "melta",
    "range": 10,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "2d10+10",
    "damageType": "energy",
    "penetration": 12,
    "clip": {"max": 3, "value": 3},
    "reload": "Full",
    "special": {"melta": true}
}, {
    "name": "Meltagun",
    "availability": "Very Rare",
    "weight": 15,
    "class": "basic",
    "type": "melta",
    "range": 20,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "2d10+10",
    "damageType": "energy",
    "penetration": 12,
    "clip": {"max": 5, "value": 5},
    "reload": "Full",
    "special": {"melta": true}
}, {
    "name": "Plasma Gun",
    "availability": "Very Rare",
    "weight": 18,
    "class": "basic",
    "type": "plasma",
    "range": 90,
    "rateOfFire": {"single": 1, "burst": 2, "full": 0},
    "damage": "1d10+7",
    "damageType": "energy",
    "penetration": 6,
    "clip": {"max": 40, "value": 40},
    "reload": "5 Full",
    "special": {"maximal": true, "overheats": true}
}, {
    "name": "Plasma Pistol",
    "availability": "Very Rare",
    "weight": 4,
    "class": "pistol",
    "type": "plasma",
    "range": 30,
    "rateOfFire": {"single": 1, "burst": 2, "full": 0},
    "damage": "1d10+6",
    "damageType": "energy",
    "penetration": 6,
    "clip": {"max": 10, "value": 10},
    "reload": "3 Full",
    "special": {"maximal": true, "overheats": true}
}, {
    "name": "Sentinel Plasma Rifle",
    "availability": "Extremely Rare",
    "weight": 20,
    "class": "basic",
    "type": "plasma",
    "range": 120,
    "rateOfFire": {"single": 1, "burst": 5, "full": 10},
    "damage": "1d10+5",
    "damageType": "energy",
    "penetration": 3,
    "clip": {"max": 40, "value": 40},
    "reload": "Full",
    "special": {"reliable": true}
}, {
    "name": "Desoleum Power Blade",
    "availability": "Very Rare",
    "weight": 2,
    "class": "melee",
    "type": "power",
    "range": 0,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "1d10+3",
    "damageType": "energy",
    "penetration": 5,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"power-field": true}
}, {
    "name": "Desoleum Power Blade",
    "availability": "Very Rare",
    "weight": 2,
    "class": "melee",
    "type": "power",
    "range": 0,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "1d10+3",
    "damageType": "energy",
    "penetration": 5,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"power-field": true}
}, {
    "name": "Ebenus Hammer",
    "availability": "Near Unique",
    "weight": 16,
    "class": "melee",
    "type": "power",
    "range": 0,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "2d10+6",
    "damageType": "energy",
    "penetration": 10,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"daemonbane": true, "power-field": true, "unwieldy": true}
}, {
    "name": "Omnissian Axe",
    "availability": "Extremely Rare",
    "weight": 8,
    "class": "melee",
    "type": "power",
    "range": 0,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "2d10+4",
    "damageType": "energy",
    "penetration": 6,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"power-field": true, "two-handed": true, "unbalanced": true}
}, {
    "name": "Ordo Malleus Power Glaive",
    "availability": "Extremely Rare",
    "weight": 0,
    "class": "melee",
    "type": "power",
    "range": 0,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "1d10+8",
    "damageType": "energy",
    "penetration": 5,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"balanced": true, "power-field": true, "proven": 4, "sanctified": true}
}, {
    "name": "Power Axe",
    "availability": "Very Rare",
    "weight": 6,
    "class": "melee",
    "type": "power",
    "range": 0,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "1d10+7",
    "damageType": "energy",
    "penetration": 7,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"power-field": true, "two-handed": true, "unbalanced": true}
}, {
    "name": "Power Fist",
    "availability": "Very Rare",
    "weight": 13,
    "class": "melee",
    "type": "power",
    "range": 0,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "2d10",
    "damageType": "energy",
    "penetration": 9,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"power-field": true, "unwieldy": true}
}, {
    "name": "Power Maul (High)",
    "availability": "Very Rare",
    "weight": 0,
    "class": "melee",
    "type": "power",
    "range": 0,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "1d10+5",
    "damageType": "energy",
    "penetration": 4,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"power-field": true, "shocking": true}
}, {
    "name": "Power Maul (Low)",
    "availability": "Very Rare",
    "weight": 0,
    "class": "melee",
    "type": "power",
    "range": 0,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "1d10+1",
    "damageType": "energy",
    "penetration": 2,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"shocking": true}
}, {
    "name": "Power Shield",
    "availability": "Extremely Rare",
    "weight": 6,
    "class": "melee",
    "type": "power",
    "range": 0,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "1d10",
    "damageType": "energy",
    "penetration": 1,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"defensive": true, "power-field": true}
}, {
    "name": "Power Stake",
    "availability": "Very Rare",
    "weight": 1,
    "class": "melee",
    "type": "power",
    "range": 0,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "1d10+7",
    "damageType": "energy",
    "penetration": 5,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"power-field": true, "sanctified": true, "unbalanced": true}
}, {
    "name": "Power Sword",
    "availability": "Very Rare",
    "weight": 3,
    "class": "melee",
    "type": "power",
    "range": 0,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "1d10+5",
    "damageType": "energy",
    "penetration": 5,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"balanced": true, "power-field": true}
}, {
    "name": "Thunder Hammer",
    "availability": "Very Rare",
    "weight": 16,
    "class": "melee",
    "type": "power",
    "range": 0,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "2d10+4",
    "damageType": "energy",
    "penetration": 10,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"concussive": 2, "power-field": true, "unwieldy": true}
}, {
    "name": "Electro-Flail",
    "availability": "Rare",
    "weight": 0,
    "class": "melee",
    "type": "shock",
    "range": 0,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "1d10+2",
    "damageType": "rending",
    "penetration": 0,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"flexible": true, "shocking": true}
}, {
    "name": "Shock Maul",
    "availability": "Scarce",
    "weight": 0,
    "class": "melee",
    "type": "shock",
    "range": 0,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "1d10+3",
    "damageType": "impact",
    "penetration": 0,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"shocking": true}
}, {
    "name": "Shock Whip",
    "availability": "Extremely Rare",
    "weight": 3,
    "class": "melee",
    "type": "shock",
    "range": 3,
    "rateOfFire": {"single": 0, "burst": 0, "full": 0},
    "damage": "1d10+1",
    "damageType": "impact",
    "penetration": 0,
    "clip": {"max": 0, "value": 0},
    "reload": "",
    "special": {"flexible": true, "shocking": true}
}, {
    "name": "Autocannon",
    "availability": "Very Rare",
    "weight": 40,
    "class": "heavy",
    "type": "solidprojectile",
    "range": 300,
    "rateOfFire": {"single": 1, "burst": 3, "full": 0},
    "damage": "3d10+8",
    "damageType": "impact",
    "penetration": 6,
    "clip": {"max": 24, "value": 24},
    "reload": "2 Full",
    "special": {"reliable": true}
}, {
    "name": "Autogun",
    "availability": "Average",
    "weight": 5,
    "class": "basic",
    "type": "solidprojectile",
    "range": 100,
    "rateOfFire": {"single": 1, "burst": 3, "full": 10},
    "damage": "1d10+3",
    "damageType": "impact",
    "penetration": 0,
    "clip": {"max": 30, "value": 30},
    "reload": "Full",
    "special": {}
}, {
    "name": "Autopistol",
    "availability": "Average",
    "weight": 0,
    "class": "pistol",
    "type": "solidprojectile",
    "range": 30,
    "rateOfFire": {"single": 1, "burst": 0, "full": 6},
    "damage": "1d10+2",
    "damageType": "impact",
    "penetration": 0,
    "clip": {"max": 18, "value": 18},
    "reload": "Full",
    "special": {}
}, {
    "name": "Hand Cannon",
    "availability": "Scarce",
    "weight": 3,
    "class": "pistol",
    "type": "solidprojectile",
    "range": 35,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "1d10+4",
    "damageType": "impact",
    "penetration": 2,
    "clip": {"max": 5, "value": 5},
    "reload": "2 Full",
    "special": {}
}, {
    "name": "Heavy Stubber",
    "availability": "Rare",
    "weight": 30,
    "class": "heavy",
    "type": "solidprojectile",
    "range": 100,
    "rateOfFire": {"single": 0, "burst": 0, "full": 8},
    "damage": "1d10+4",
    "damageType": "impact",
    "penetration": 3,
    "clip": {"max": 80, "value": 80},
    "reload": "2 Full",
    "special": {}
}, {
    "name": "Shotgun",
    "availability": "Average",
    "weight": 5,
    "class": "basic",
    "type": "solidprojectile",
    "range": 30,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "1d10+4",
    "damageType": "impact",
    "penetration": 0,
    "clip": {"max": 8, "value": 8},
    "reload": "2 Full",
    "special": {"scatter": true}
}, {
    "name": "Shotgun (Combat)",
    "availability": "Scarce",
    "weight": 0,
    "class": "basic",
    "type": "solidprojectile",
    "range": 30,
    "rateOfFire": {"single": 1, "burst": 3, "full": 0},
    "damage": "1d10+4",
    "damageType": "impact",
    "penetration": 0,
    "clip": {"max": 18, "value": 18},
    "reload": "Full",
    "special": {"scatter": true}
}, {
    "name": "Sniper Rifle",
    "availability": "Scarce",
    "weight": 5,
    "class": "basic",
    "type": "solidprojectile",
    "range": 200,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "1d10+4",
    "damageType": "impact",
    "penetration": 3,
    "clip": {"max": 20, "value": 20},
    "reload": "Full",
    "special": {"accurate": true, "reliable": true}
}, {
    "name": "Stub Automatic",
    "availability": "Average",
    "weight": 0,
    "class": "pistol",
    "type": "solidprojectile",
    "range": 30,
    "rateOfFire": {"single": 1, "burst": 3, "full": 0},
    "damage": "1d10+3",
    "damageType": "impact",
    "penetration": 0,
    "clip": {"max": 9, "value": 9},
    "reload": "Full",
    "special": {}
}, {
    "name": "Stub Revolver",
    "availability": "Plentiful",
    "weight": 0,
    "class": "pistol",
    "type": "solidprojectile",
    "range": 30,
    "rateOfFire": {"single": 1, "burst": 0, "full": 0},
    "damage": "1d10+3",
    "damageType": "impact",
    "penetration": 0,
    "clip": {"max": 6, "value": 6},
    "reload": "2 Full",
    "special": {"reliable": true}
}]
